### PR TITLE
Shared Room and Rate

### PR DESCRIPTION
**Pull request by mihonninja**
Issue: https://github.com/ubio/squad-smart-feed/issues/627

### CODE REVIEW

**Comment by mihonninja** [comment]
@nicck I've tried to build it locally with docker and I can see changes in built files, but not on actual site for some reason. Since you're the guy who introduce docker-compose here it would be great to have a quick chat about it on Monday after-standup party.

**Comment by nicck** [comment]
> @nicck I've tried to build it locally with docker and I can see changes in built files, but not on actual site for some reason. Since you're the guy who introduce docker-compose here it would be great to have a quick chat about it .

Does this bit from [README](https://github.com/ubio/protocol#quick-start) helps?
>  Additionally, protocol URL is hardcoded and points to production environment, thus you may **need to temporary override it to see changes on http://localhost:8080/.**

**Comment by mihonninja** [comment]
🤔 Screenshot 2023-05-10 at 17 17 58

**Comment by mihonninja** [comment]
@nicck I'm not sure you're right about `description`. We have several `Rate` fields without it: `breakfastIncluded`, `lunchIncluded`, `dinnerIncluded`, `allInclusive`, `parkingIncluded`, `internetIncluded`. And I tried to add description and nothing changes =(

**Review by nicck — APPROVED** [review]

**Pull request merged**
